### ISSUE TITLE
Wrong ip checking - Spain

### ISSUE THREAD

**Issue by BigLes** [bluesmoon/node-geoip#102]
According to [GeoIpTool](https://geoiptool.com/en/?ip=50.7.82.66), ip "50.7.82.66" is from Spain, but package gives 
`{"range":[839340032,839344127],"country":"US","region":"IL","city":"Chicago","ll":[41.8776,-87.6272],"metro":602}`.
Checked on maxmind site, it says that in both databases this ip address registered as from Spain.

**Comment by bluesmoon** [comment]
update your database

**Comment by BigLes** [comment]
Thanks.
Something is wrong with my update script. Update manually works fine.

**Comment by JanAhrend** [comment]
@BigLes Excuse me for the nooby question, how do I manually update the database?
