### ISSUE TITLE
Maxmind's ISP integration

### ISSUE THREAD

**Issue by nicocepi** [bluesmoon/node-geoip#103]
Have you ever made an implementation with the maxmind's ISP database in order to identify the internet provider of the IP?

Thanks

**Comment by bluesmoon** [comment]
Technically no, since the ISP database isn't free, I didn't write the code to parse it.  That said, however, the ISP csv format (which I have seen, but don't have access to at the moment) is very similar to the country database, so it would not be hard to copy the country parsing code and generate ISP parsing code if you wanted to take a stab at it.

**Comment by oschwald** [comment]
Unfortunately, the ISP and organization databases are significantly different than country as far as data structure goes. Similar to the city database, they have a data section at the end but each data record is string. They also have a different node record size than both Country and City. There are test databases available in most of the MaxMind client API repos.

**Comment by bluesmoon** [comment]
is this for legacy GeoIP or GeoIP2?  I haven't looked at GeoIP2 unfortunately.

**Comment by oschwald** [comment]
My comment was for Legacy. GeoIP2 is a completely different format.

**Comment by nicocepi** [comment]
if I buy the latest ISP database from Maxmind, could you take a look on it?

**Comment by oschwald** [comment]
[Test databases](https://github.com/maxmind/geoip-api-python/tree/master/tests/data) for the different legacy formats.

**Comment by bluesmoon** [comment]
@oschwald that url does not contain the CSVs.  We only work with CSVs.

**Comment by bluesmoon** [comment]
@nicocepi I don't have the time to add features to the project, but I have time to code review, merge and release new npm packages.

**Comment by oschwald** [comment]
Ah, sorry about that, I didn't realize that this API used a custom binary format.

**Comment by bluesmoon** [comment]
Marking as a dup of #97
