### ISSUE TITLE
Remove unzip dependency.

### ISSUE THREAD

**Issue by DylanPiercey** [bluesmoon/node-geoip#107]
https://www.npmjs.com/package/unzip hasn't been updated for 2 years and depends on an old version of "fstream -> graceful-fs" which currently fails in node 6.

A replacement is needed for full node 6 compatibility.

**Comment by bluesmoon** [comment]
Can you check if this library works? https://www.npmjs.com/package/unzip-wrapper

It seems that all of the unzip libraries on npm are over a year old, and most are just clones of the one we use, but this one is a wrapper around the native unzip program, so may work out better.  If all fails, we can just `exec` the native unzip.

**Comment by gtebbutt** [comment]
It looks like the `unzip` dependency is now causing the update script to fail on Node 10.x.x with the following:
```
void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
```

I'm going to take a look at whether https://www.npmjs.com/package/yauzl works - it seems the most popular and well-maintained zip library I could find
