### ISSUE TITLE
Some IPs return wrong/empty information

### ISSUE THREAD

**Issue by ronanww** [bluesmoon/node-geoip#108]
Some IPs return wrong/empty information, for example when I do **geoip.lookup("74.64.22.166")** I get

```
{ 
  range: [ 1245713920, 1245714175 ],
  country: 'US',
  region: '',
  city: '',
  ll: [ 37.751, -97.822 ],
  metro: 0
}
```

However when I use MaxMind demo https://www.maxmind.com/en/geoip-demo for the same IP I get the following information

```
74.64.22.166
US
New York,
New York,
United States,
North America
10022
40.7588, -73.968
10
Time Warner Cable
Time Warner Cable
rr.com
501
```

How can I ensure the same information getting return from geoip-lite?

**Comment by bluesmoon** [comment]
Make sure you have the latest version of the GeoIP database from the MaxMind site.  You can use the update script to get the latest version.

However note that MaxMind's website demo uses the commercial database and not the free database. To get the same results you might have to pay maxmind for their commercial database and then convert it using our conversion tool.  You'll need to get the CSV formats of the country and city databases.

**Comment by ronanww** [comment]
@bluesmoon I have already updated the databases with your update scripts. However it still doesn't show the right location. I tried to used other solutions like https://www.npmjs.com/package/satelize and http://freegeoip.net/json/ but I still get the same response. I guess it is probably what you just said about the commercial vs free database
