### ISSUE TITLE
Specify typical memory use

### ISSUE THREAD

**Issue by ashconnell** [bluesmoon/node-geoip#110]
The readme says that it uses lots of memory, are we talking gigabytes?

**Comment by bluesmoon** [comment]
somewhere between 512MB and 2GB.

**Comment by zbmowrey** [comment]
Is that per running process, or do process share access to the database in memory?

**Comment by bluesmoon** [comment]
It depends on how you start new processes. If you start them all independently, then they'll each have their own copy in memory. Instead if you start one process, read the data into memory and then fork multiple processes, they'll all share the same memory as long as you don't write to that datastructure.

**Comment by bluesmoon** [comment]
IPC would make the master a bottleneck. Shared memory would be good, but will need a lock when updatedb is running since I assume that we'd only want one process (probably a new process) to update the shared db.

**Comment by ar2rsawseen** [comment]
ok, got it. By the way, just for reference for this issue:

```
var geoip = require('geoip-lite');
console.log(process.memoryUsage());
```
results in
```
{ rss: 136409088,
  heapTotal: 10305536,
  heapUsed: 5178768,
  external: 106148840 }
```
So pure data seems to only consume around 100Mb

**Comment by bluesmoon** [comment]
Thanks, let's put this in the README.  I think I added that comment because a lot of people tried running it on the smallest Digital Ocean droplet they could get and it just didn't have enough RAM to store the db in memory.

**Comment by ar2rsawseen** [comment]
Added it here: https://github.com/bluesmoon/node-geoip/pull/167
