### ISSUE TITLE
Local variant of updatedb command not working

### ISSUE THREAD

**Issue by slavafomin** [bluesmoon/node-geoip#113]
Hello!

Thank you for this great library!

However, the command `node ./node_modules/geoip-lite/scripts/updatedb.js` from the README does nothing on my machine.

`npm run-script updatedb` works fine.

```
$ node --version
v7.1.0
```

Thanks!

**Comment by bluesmoon** [comment]
That's intentional.  Notice these lines right at the top of the script:

```javascript
if(!process.env.npm_package_config_update){
	return;
}
```
