### ISSUE TITLE
Updatedb script and HTTPS proxy

### ISSUE THREAD

**Issue by lneveu** [bluesmoon/node-geoip#116]
Hi!

I'm experiencing some issues with the **updatedb** script. I use a https proxy and when I launched the script, I've got this error:

`Error: Protocol "http:" not supported. Expected "https:"`

So, I've check the code and I've found something wrong:

[Here](https://github.com/bluesmoon/node-geoip/blob/master/scripts/updatedb.js#L108), as all the requests are using the https protocole, I think you need to check the `https_proxy` env variable and use it instead of `http_proxy`.
	
You probably need to use the [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) package in order to use a proxy with HTTPS requests.
(@see http://blog.vanamco.com/proxy-requests-in-node-js)

I've tested it and it works well :)

**Comment by bluesmoon** [comment]
Thanks for checking. If you could submit a patch, I'd be happy to merge it
in.

**Comment by lneveu** [comment]
Done @ #117 👍

**Comment by lneveu** [comment]
Hi!
Are you planning to release a new version of node-geoip soon?

Thx!

**Comment by bluesmoon** [comment]
done
