### ISSUE TITLE
Question about lookup response

### ISSUE THREAD

**Issue by maZahaca** [bluesmoon/node-geoip#118]
I did a Moscow IP lookup
Results are stated below:
```json
{"range":[3588800512,3588802559],"country":"RU","region":"48","city":"Moscow","ll":[55.752,37.615],"metro":0}
```
Could you clarify about `region` and `metro`?
* metro isn't documented
* region - documented, but it should be a code in a different format (FIPS)

**Comment by bluesmoon** [comment]
The values are whatever MaxMind returns. Documentation should be on their
site.

**Comment by bluesmoon** [comment]
For more details, see http://geolite.maxmind.com/download/geoip/misc/region_codes.csv (RU.48 == Moscow City)

Metro code is US only apparently according to https://www.maxmind.com/en/geoip2-city
