### ISSUE TITLE
How to get zip code?

### ISSUE THREAD

**Issue by ScaryWolfMan** [bluesmoon/node-geoip#119]
Just wondering how to get the zip code instead of city name.

I am looking at the code and in the lib/, but having some trouble.  I am curious if the maxmind api does return zip codes as well.  

Thanks

**Comment by bluesmoon** [comment]
I believe MaxMind does include the zip code in its GeoIP2 database, but this library only includes metro code (https://support.google.com/richmedia/answer/2745487).

**Comment by ScaryWolfMan** [comment]
Thanks.  Is there a way for me to change anything in this library to get zip code?  I am just trying to get a little bit more precise location.  Regards

**Comment by bluesmoon** [comment]
You'll have to change almost all parts of the code.  We transform MaxMind's data files into our own format, and we drop the zip code at that point, so you'll have to change the code that does this transformation, and then change the code that reads the data files, but you'll probably also want to be backwards compatible with the old data files.

**Comment by workheap** [comment]
I am also interested in this feature, ready to collaborate in development. Would you consider pull request or you have objections against this (e.g. performance issues, backward compatibility, etc)?

Thank you!

**Comment by bluesmoon** [comment]
I will accept a pull request if you send one.

**Comment by bluesmoon** [comment]
Closed with #122
