### ISSUE TITLE
expose updatedb as binary using npm

### ISSUE THREAD

**Issue by crunchie84** [bluesmoon/node-geoip#124]
`geoip-lite 1.2.0` 

Currently i am facing some issues because one of my (npm) packages used in my project depends on geoip-lite. I want to invoke `updatedb` but somehow NPM has not installed `geoip-lite` inside a node_modules folder underneath the dependency but into the root node_modules folder.

This makes it hard to locate the correct folder and invoke updatedb. 

When you specify that updatedb is a binary to be invoked it can be aliased so within your `package.json` you can simply execute `updatedb`. This is the same behaviour as done by packages like `mocha` or `nsp`.

http://blog.npmjs.org/post/118810260230/building-a-simple-command-line-tool-with-npm

**Comment by bluesmoon** [comment]
Did you try `npm run-script updatedb` ?
