### ISSUE TITLE
missing dependency fs

### ISSUE THREAD

**Issue by VinceG** [bluesmoon/node-geoip#125]
Maybe i am missing something but fs is not a dependency. when i try to run geoip-lite it returns the following

```
This dependency was not found:

* fs in ./~/geoip-lite/lib/geoip.js, ./~/geoip-lite/lib/fsWatcher.js
```

any ideas? Thank You.

**Comment by bluesmoon** [comment]
which version of node are you using?  `fs` is part of the node core libraries.

**Comment by VinceG** [comment]
node 7.7.1
npm 4.2.0

**Comment by bluesmoon** [comment]
I wonder if you're being hit by #111, which is a problem in some upstream package but I don't know which one.

**Comment by VinceG** [comment]
@bluesmoon i am not entirely sure what that means. but even if i try the below code it fails with the same error.

```
//let geo = require('geoip-lite');
let fs = require('fs');
```

i've noticed this happens with any package i try to use that is dependent on fs. even by trying to call it myself.

**Comment by bluesmoon** [comment]
sorry I don't understand,  where is this code?

If this is happening outside of geoip-lite, then I'd recommend contacting the node.js team.

**Comment by VinceG** [comment]
it is not specific to geoip-lite as i now understand. anything that calls to 'fs' returns that error. i'll try opening a ticket at the nodejs repository.

Thank You.

**Comment by bluesmoon** [comment]
I just tried running the test programs with node 7.7.4 and had no problem, so this is not a geoip-lite issue.  Chances are you have something stomping on the system installed `fs`

**Comment by ktquez** [comment]
I have the same problem.
