### ISSUE TITLE
locale is not correct for 103.211.93.170

### ISSUE THREAD

**Issue by huyntsgs** [bluesmoon/node-geoip#129]
I am in vietnam, when i submit this ip it report HK. could you please check it. Thanks
http://geobytes.com/iplocator/ gives correct result.

**Comment by bluesmoon** [comment]
MaxMind reports this IP as Hong Kong and IP Locator reports it as Brisbane, QLD, Australia.

I would suggest you report the bug to MaxMind.  We do not have any control over what they put in the database, we only provide bindings for node.js.
