### ISSUE TITLE
'native' module is required

### ISSUE THREAD

**Issue by JarnoVgr** [bluesmoon/node-geoip#130]
In order to run the `npm run-script updatedb` the 'native' module is required, but it isn't specified in the package.json file. This should be included, if I'm not mistaken.

**Comment by bluesmoon** [comment]
I'm not aware of the native module or why it is required.  I don't believe we use it internally.

**Comment by JarnoVgr** [comment]
Well, the module was missing when running that command. Adding it to this packages package.json, rerunning npm install and then the command made it work just fine. (Ubuntu 16.04 LTS x64)

I'll try to reproduce the error tomorrow or so.

**Comment by ar2rsawseen** [comment]
If issue persists, please reopen
