### ISSUE TITLE
Geoip.lookup() returns null

### ISSUE THREAD

**Issue by DeclanMurphyCit** [bluesmoon/node-geoip#131]
The following returns a null object:
`geoip.lookup(154.146.66.33)`

This website is able to retrieve data about it however? http://whatismyipaddress.com/ip/154.146.66.33

**Comment by bluesmoon** [comment]
do you have an up to date geoip database from MaxMind?

**Comment by DeclanMurphyCit** [comment]
I have `"geoip-lite": "^1.1.6",`.
If I update this to the latest version will the MaxMind database also be updated?

**Comment by bluesmoon** [comment]
The database has to be updated separately from the library (see step 2 in the README file).  MaxMind updates the database once a month.  Most people set up an auto update.  The README file has information about all of this.

**Comment by DeclanMurphyCit** [comment]
Ok thanks, sorry for the hassle, I should have figured this myself.
