### ISSUE TITLE
weird line

### ISSUE THREAD

**Issue by FranckFreiburger** [bluesmoon/node-geoip#143]
Just note that I get the following message when updating the database with `npm run-script updatedb`:
...
`Extracting GeoLite2-City-CSV.zip ...weird line: 703656,en,EU,Europe,UA,Ukraine,63,"Kharkivs'ka Oblast'",,,"Kup""yans'k",,Europe/Kiev,0::`
...

**Comment by bluesmoon** [comment]
it's probably the `""` inside `Kup""yans'k`

**Comment by FranckFreiburger** [comment]
I think so, however I am sure it is a beautiful city.

**Comment by nezed** [comment]
@FranckFreiburger yep, probably. 
These is some photos of “Харьков, Купянск”

<img src="https://user-images.githubusercontent.com/1659008/45001429-ae2ed600-afd5-11e8-815a-16e84f9f293c.jpeg" width=400 />

<img src="https://user-images.githubusercontent.com/1659008/45001430-ae2ed600-afd5-11e8-9ca5-993007a42b01.jpeg" width=400 />

**Comment by ar2rsawseen** [comment]
This lib has a custom CSV parser which already deals with many special cases, but this is just 😱

**Comment by ar2rsawseen** [comment]
The line is ignored yes when processed, no data corruption
the only problem is that the end data does not include that line, so IP address range for Kupyansk is missing from database :)

**Comment by oschwald** [comment]
The line is not corrupt. The [RFC-approved way](https://tools.ietf.org/html/rfc4180#section-2) to escape a `"` in CSVs is with another `"`. Most CSV parsers support this escaping.

**Comment by oschwald** [comment]
@bluesmoon, sorry, I did not mean to imply that you said this. I was responding to the question above about whether the file was corrupt.

**Comment by ar2rsawseen** [comment]
Since Kupyansk seems to be a nice place, let's try to fix it :)
https://github.com/bluesmoon/node-geoip/pull/157

**Comment by ar2rsawseen** [comment]
This issue has been fixed
