### ISSUE TITLE
country by IP not found

### ISSUE THREAD

**Issue by Laboratory** [bluesmoon/node-geoip#146]
Hello, 

Maxmind got country and location from this IP: `80.254.155.83` https://www.maxmind.com/en/geoip2-precision-demo?ip=80.254.155.83

But, this package doesn't have information regarding this IP;

What is wrong? 

Thx, V

**Comment by bluesmoon** [comment]
which version of geoip-lite are you using and do you have the latest database?  Note that MaxMind on their own site uses the commercial database, not the free one, so you'll have to buy that to get the same results.

**Comment by Laboratory** [comment]
version of package 1.3.2 and latest database but city doesn't exist

**Comment by ar2rsawseen** [comment]
Updated database and ran your IP address:
```
Checking IP: 80.254.155.83
{ range: [ 1358863187, 1358863187 ],
  country: 'CH',
  region: '',
  eu: '0',
  timezone: 'Europe/Zurich',
  city: '',
  ll: [ 47.1449, 8.1551 ],
  metro: 0,
  area: 1000 }
```

Seems to be working fine
The website shows result form paid database, so it could be due to that, it has changes much sooner and much better results. Or your local db is out of date.
