### ISSUE TITLE
GeoLite2 Data License Possibly Outdated

### ISSUE THREAD

**Issue by santiagoecheverri94** [bluesmoon/node-geoip#147]
Hi @bluesmoon  ,

First, thanks a lot for developing this package. I have found it very useful!

I wanted to ask about the license for the GeoLite2 database used. 

Currently, the [license file](https://github.com/bluesmoon/node-geoip/blob/master/LICENSE) for geoip-lite says that the database is licensed under the **"Open Data License."**

However, the [GeoLite2 database's website](https://dev.maxmind.com/geoip/geoip2/geolite2/) says it is licensed under **"Creative Commons Attribution-ShareAlike 4.0 International License"**

I wanted to please ask if maybe the database license was out of date in the License file for this repo, or if I am missing something and the license is indeed the Open Data License?

Thanks!

**Comment by bluesmoon** [comment]
We haven't updated the licence file when we updated to v2, so it's quite likely out of date. Can you submit a PR with the change?

**Comment by santiagoecheverri94** [comment]
Thanks for prompt reply @bluesmoon 

Sure, I created https://github.com/bluesmoon/node-geoip/pull/149, suggesting an update for the new GeoLite2 Databases license

**Comment by santiagoecheverri94** [comment]
Closing since LICENSE in now updated. Thanks @bluesmoon !
