### ISSUE TITLE
region not returning state when in US

### ISSUE THREAD

**Issue by code-a-cola** [bluesmoon/node-geoip#150]
The region code for US based IP addresses is not returning state abbreviations, but instead returns NA for every response. I've tested this using several different US based IP addresses.

This is just an example response, but the results are the same for all US IP addresess:

{
    "range": [
        3322362624,
        3322362879
    ],
    "country": "US",
    **"region": "NA",**
    "eu": "0",
    "timezone": "America/New_York",
    "city": "Manassas",
    "ll": [
        38.7701,
        -77.6321
    ],
    "metro": 511,
    "area": 1000
}

I am on the most current version for both geoip-lite and the database.

In your documentation you state that US region will return states, is this no longer the case?

**Comment by culli** [comment]
This appears to be a regression on #141 , fixed in 1.3.2, but broken again?

**Comment by culli** [comment]
1.3.2 has a vulnerability, so that is not an option, see #153

**Comment by bluesmoon** [comment]
The only code change between 1.3.2 and 1.3.4 is changing `new Buffer` to `Buffer.alloc` so I doubt that has made a difference to this.

**Comment by bluesmoon** [comment]
It's safe to use 1.3.2.  While we depend on the `save` package, we don't actually use it anywhere so we're not affected by any potential vuln.

**Comment by ar2rsawseen** [comment]
This is probably due to change to GeoIP 2
Then I guess region should be `subdivision_1_iso_code` from GeoLite2-City-CSV
which would be state code in USA and something else in other countries.

That is fixable, let me check it

**Comment by ar2rsawseen** [comment]
Should be fixed here: https://github.com/bluesmoon/node-geoip/pull/154

**Comment by ar2rsawseen** [comment]
This issue has been fixed

**Comment by shaneRealPropRt** [comment]
Thank you!!!!!
