### ISSUE TITLE
Poisoned event-stream dependency

### ISSUE THREAD

**Issue by oliversalzburg** [bluesmoon/node-geoip#153]
This is regarding https://github.com/dominictarr/event-stream/issues/116

`geoip-lite` depends on `save@^2.3.2` which depends on `event-stream@^3.3.4`. This had the potential to resolve its dependency on `flatmap-stream@^0.1.0` to a version that included the malware.

**Comment by bluesmoon** [comment]
can you submit an MR to fix?

**Comment by oliversalzburg** [comment]
I'm not sure how. `save` would have to be updated to use `event-stream@^4.0.0`, but the package doesn't mention a repo. Maybe the package could also be downgraded to a version that will use older versions of the dependency.

Or `save` would have to be replaced here entirely. But I haven't yet looked into what purpose it serves here. I mostly wanted to make people aware of this issue.

**Comment by bluesmoon** [comment]
@ar2rsawseen do you have any idea?

**Comment by bluesmoon** [comment]
It doesn't appear as if we're even using `save` even though it's included in `package.json`.  Maybe I'll just take it out.

**Comment by ar2rsawseen** [comment]
Right, I think it was a leftover after a failed attempt on caching approach. Sorry for that.
