### ISSUE TITLE
Update or just download?

### ISSUE THREAD

**Issue by GHNewbiee** [bluesmoon/node-geoip#156]
Hi,

I updated the databases as per your instructions. Just after completion I run the script again, and the same files were downloaded again.

So, my question is: when you write update you just mean download or it's a procedure a little bit more sophisticated which checks if the files have been changed and then start downloading.

Tia

**Comment by ar2rsawseen** [comment]
Hello,
so usually the release incorporates the latest data at the time of last commit/merge, etc

But if more time than 30 days have passed, most probably some data is already outdated, and you should update database.

Updating downloads latest CSV files from MaxMind and regenerates .dat files from scratch.

If afterwards in git diff you can't see changes, most probably package already had latest data and nothing new was added.

But update always downloads files and regenerates .dat files without any checks

**Comment by GHNewbiee** [comment]
Hence, I suggest, for sake of clarity and avoidance of misinterpretation, an easily distinguishable clarification to be added making clear how the term "update" is interpreted/considered/used by the current project.

**Comment by ar2rsawseen** [comment]
Added information in readme here:
Submitted fix here: https://github.com/bluesmoon/node-geoip/pull/167
