### ISSUE TITLE
Update enhancement

### ISSUE THREAD

**Issue by GHNewbiee** [bluesmoon/node-geoip#158]
Hello,

**"Update"** procedure to be enhanced with **md5 checksum** comparison or any other manner so that downloading of the same `.csv` files to be avoided.

**Comment by ar2rsawseen** [comment]
Like the idea
I think we can store checksum of zips somewhere locally

And check them here before loading:
https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.md5
https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.md5

If nobody does this, will try to do it over next spare weekend

**Comment by GHNewbiee** [comment]
For a long time now, this is the only positive attitude I have met, although you are not the "owner" of the project!

PS: I will remove this comment after 2-3 days.

**Comment by ar2rsawseen** [comment]
Due to our product relying on libs for which maintainers don't have enough time anymore, I have been supporting many other project 😃 
In this case @bluesmoon is kind enough to actually review and accept PRs
Most projects won't even accept PRs anymore and won't reply to emails, so we have to fork them and maintain our own forks. Which is sad, because possibly many other devs also relying on those libs might not even know about the changes, etc.

**Comment by ar2rsawseen** [comment]
And don't remove your comment, it is nice and encouraging, and I bet @bluesmoon does not take it personally.

**Comment by GHNewbiee** [comment]
**General speaking**, when an (initial) developer/maintainer does not have enough time (or for any other reason) to support a **published** project **under a permissive license**, inho, (s)he should, **at least, publish it** and call other developers for adoption, if (s)he does like so. In that case, other developers have the right to fork and rename it, if they decide so, and continue the development acknowledging the initial developer(s) and project; in turn, the initial developer(s) would place a link to the new project, if (s)he does like so. This is how I understand the OS ecosystem!

PS: To be honest, the purpose of my comment was **absolutely not** to encourage you or other people to start making PRs in this or any other **private** project. I am totally against that for various reasons! I just pointed your positive attitude to agree with/accept a feature request as a good idea!

**Not generally speaking**: Of course, what I suggested was not even, for me, an "idea"; it is an **obvious logical weakness/bug** which should not even exist from the birth of the project! In 2019, downloading the same file twice in blind is a very very poor implementation!

**Comment by ar2rsawseen** [comment]
Wow, you know how to ruin the mood 😃

**Comment by bluesmoon** [comment]
@GHNewbiee do you have a newsletter I can subscribe to?

@ar2rsawseen what say we make it official and I add you as a maintainer? If you can figure out how to do this on npm, then I'll add you there too.  I'll still do code reviews though.

**Comment by ar2rsawseen** [comment]
Yay, finally I will be able to get through all those stale issues and PR that have been opened for too long and completely out of date 😄 
And I am ok submitting contributions through PRs, so just you could take a look too

About npm, sure have published some packages there too:
https://www.npmjs.com/~ar2rsawseen

but I guess in most cases you want to do publishing yourself, and I can step in only in case it is urgent or you are not available.

**Comment by ar2rsawseen** [comment]
Submitted PR here:
https://github.com/bluesmoon/node-geoip/pull/164

**Comment by ar2rsawseen** [comment]
This has been merged and released in 1.3.6
