### ISSUE TITLE
Incomplete/truncated timezone

### ISSUE THREAD

**Issue by gaston-a-flores** [bluesmoon/node-geoip#161]
Using geoip-lite 1.3.5

When using geoip to lookup the IP **190.18.65.12** the returned timezone is truncated

Expected result: `timezone: 'America/Argentina/Buenos_Aires',`

Actual result: `timezone: 'America/Argentina/Buenos',`

**Comment by ar2rsawseen** [comment]
Confirming, we are only reserving 24 bytes for timezone. What is the longest timezone name possible?
I can just increase the size to 30 bytes, but don't want to change it on every new found zone 😄

**Comment by ar2rsawseen** [comment]
Based on this:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
the longest one is: America/Argentina/ComodRivadavia
with 32 chars
If you can't find any longer, I will update lib to use 32 chars next time I have a spare time 😃

**Comment by gaston-a-flores** [comment]
Sorry about the delay, that'd be great! I didn't know we had such long TZ strings 😅 Thank you for your help!

**Comment by ar2rsawseen** [comment]
Submitted fix here:
https://github.com/bluesmoon/node-geoip/pull/163

**Comment by ar2rsawseen** [comment]
This has been merged and released in 1.3.6
