### ISSUE TITLE
No data anymore after update Database

### ISSUE THREAD

**Issue by endbay** [bluesmoon/node-geoip#166]
Here's reproducible code, same with async/sync and filewatcher method:
```
setInterval(() => {
    const lookup = geoIp.lookup('75.82.117.180');

    if (lookup && lookup.city) {
        console.log(lookup.city);
    } else {
        console.log(lookup);
        console.log('NO CITY FOUND?');
    }
}, 1000 * 2);


setTimeout(() => {
    geoIp.reloadData(function () {
        console.log('GEOIP Done!');
    });
}, 10 * 1000);

```

Log looks like:
```
0|DEV_API  | Valley Village
0|DEV_API  | Valley Village
0|DEV_API  | Valley Village
0|DEV_API  | Valley Village
0|DEV_API  | GEOIP Done!
0|DEV_API  | null
0|DEV_API  | NO CITY FOUND?
0|DEV_API  | null
0|DEV_API  | NO CITY FOUND?
0|DEV_API  | null
0|DEV_API  | NO CITY FOUND?
0|DEV_API  | null
0|DEV_API  | NO CITY FOUND?
```

This happening always. Need to restart the node application to have data again.

**Comment by ar2rsawseen** [comment]
Problem seems to be with async reload only, checking

**Comment by ar2rsawseen** [comment]
Submitted fix here: https://github.com/bluesmoon/node-geoip/pull/167

**Comment by knoxcard** [comment]
I am experiencing the same problem

**Comment by ar2rsawseen** [comment]
@bluesmoon are you ok with me reviewing/merging latest PRs and publishing new version to fix this?

**Comment by bluesmoon** [comment]
yes

**Comment by ar2rsawseen** [comment]
Merged PR, will release soon :)

**Comment by ar2rsawseen** [comment]
For some reason, I don't have access to npm publish for that module. I thought I did.
Eitherway, it is ready, just needs to be published, when you can @bluesmoon
