### ISSUE TITLE
Wrong country for EU IP address

### ISSUE THREAD

**Issue by andy-portmen** [bluesmoon/node-geoip#171]
With updated database, for "176.223.226.110" I get:

```
 range: [ 2967461888, 2967465983 ],
  country: '',
  region: '',
  eu: '0',
  timezone: 'Europe/Vaduz',
  city: '',
  ll: [ 47, 8 ],
  metro: 0,
  area: 200 }
```

Also note that if I only have country databases, `null` will be returned.

**Comment by ar2rsawseen** [comment]
Hello,
it is exactly the same that data base provider returns:
https://www.maxmind.com/en/geoip-demo

So I don't think we can do anything there on our side:
![image](https://user-images.githubusercontent.com/399992/54106418-c2b5b600-43de-11e9-9a4c-9ba48a9be6be.png)

**Comment by andy-portmen** [comment]
@ar2rsawseen so this `null` return if only country databases are loaded is also acceptable?

**Comment by ar2rsawseen** [comment]
Well, it is not in Country database at all it seems. So result seems logical.
