### ISSUE TITLE
Result different from Maxmind and wrong

### ISSUE THREAD

**Issue by mathieuh** [bluesmoon/node-geoip#172]
Hi,

Somehow passing 77.159.209.18 through https://www.maxmind.com/en/geoip-demo returns "Bordeaux" while passing the same ip address to geo-ip-lite returns "Marseille".
These cities are 600km away from each other. I believe Maxmind gives the right result.

**Comment by ar2rsawseen** [comment]
Hello,
have been maintaining tests for this library for some time now, and such switches can happen like every 30 days or so. Like every time I update the database, I also need to fix the tests too

So it is possible that
1) your local database is outdated, please run 
```
cd node_modules/geoip-lite && npm run-script updatedb
```
to update it

2) I think Maxmind gives demo from their premium database, not lite one. I don't know exact differences there, unfortunately

**Comment by mathieuh** [comment]
Thanks for your reply @ar2rsawseen, I just updated my local db and it still shows the wrong result. I think we are in the 2nd case here then.
