### ISSUE TITLE
Geoip-lite returns lat/long from Wichita, Kansas for ip In Spring, TX

### ISSUE THREAD

**Issue by beatricemendoza23** [bluesmoon/node-geoip#173]
Spring, TX IP address: 205.251.150.170

Response from geoip-lite:
{
  range: [3455817216, 3455817727],
  country: 'US',
  region: '',
  eu: '0',
  timezone: '',
  city: '',
  ll: [37.751, -97.822],
  metro: 0,
  area: 1000
}

Note that the latitude and longitude returned are from Wichita, Kansas.

**Comment by bluesmoon** [comment]
Wichita Kansas is the geographical centre of the continental united states.  It just means that the database doesn't have more accurate information for that IP.

Are you using the latest version of the MaxMind database, and is it the free or commercial version?  The free version does not have as much coverage as the commercial version. Our library works with whichever version you have.

**Comment by beatricemendoza23** [comment]
I am using the latest version of the MaxMind database, and it is the free version. Would the commercial version give back different results for this ip address?

**Comment by bluesmoon** [comment]
you can test on the MaxMind website here: https://www.maxmind.com/en/geoip-demo
It uses the commercial database.

**Comment by beatricemendoza23** [comment]
It indeed does return more accurate information. Does the commercial db also return Wichita Kansas when it doesn't have more accurate information on a particular ip address?

**Comment by bluesmoon** [comment]
Yes, that lat/long are in the database.

Technically it should be just outside Lebanon, KS, but Maxmind had a bit of a problem a few years ago:
> In an unusual technical glitch, a farmstead northeast of Potwin, Kansas, became the default site of 600 million IP addresses (due to their lack of fine granularity) when the Massachusetts-based digital mapping company MaxMind changed the putative geographic center of the contiguous United States from 39.8333333,-98.585522 to 38.0000,-97.0000.
>
> https://en.wikipedia.org/wiki/Geographic_center_of_the_contiguous_United_States

Coincidentally, the fictional town of Smallville, KS, where Superman is supposed to have grown up is also in this general area.

**Comment by beatricemendoza23** [comment]
Cool! Thanks for the info, very useful.
