### ISSUE TITLE
Not showing proper country for Ireland's IP address, rather showing GB

### ISSUE THREAD

**Issue by ashutoshkarna03** [bluesmoon/node-geoip#177]
The ip address `195.16.170.74` is from Dublin Ireland, but I am getting 
{ range: [ 3272648704, 3272650751 ],
  country: 'GB',
  region: '',
  eu: '1',
  timezone: 'Europe/London',
  city: '',
  ll: [ 51.4964, -0.1224 ],
  metro: 0,
  area: 200 }
This is from latest update of geo-ip database.

**Comment by ar2rsawseen** [comment]
I guess this is one of those cases of difference between free and premium database
From our side all seems correct, per files, it is in GB
But paid demo maxmind db says it is in Ireland
