### ISSUE TITLE
"Index out of range" exception + Former DB files urls are broken (HTTP 404)

### ISSUE THREAD

**Issue by RazYahkovnia** [bluesmoon/node-geoip#180]
Hey,

I'm using the geoip-lite version 1.1.5 and the command for updating the database is broken (npm run-script updatedb), the URL does not exist anymore (we get 404).

We tried upgrading to the latest version (1.3.7), but sometimes we see an exception in our logs that doesn't happen in the older version:

```
RangeError: Index out of range
    at checkOffset (buffer.js:831:11)
    at Buffer.readInt32BE (buffer.js:996:5)
    at lookup4 (/opt/capriza/napi/napi-581/node_modules/geoip-lite/lib/geoip.js:114:31)
    at Object.lookup (/opt/capriza/napi/napi-581/node_modules/geoip-lite/lib/geoip.js:461:11)
    at Object.process (/opt/capriza/napi/napi-581/mongo-handlers/events-processors.js:44:33)
    at /opt/capriza/napi/napi-581/mongo-handlers/stats-collector.js:134:23
    at /opt/capriza/napi/napi-581/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/opt/capriza/napi/napi-581/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/opt/capriza/napi/napi-581/node_modules/async/lib/async.js:209:22)
    at validationsDone (/opt/capriza/napi/napi-581/mongo-handlers/stats-collector.js:128:17)
```

We don't exactly know yet when this exception happens. We didn't manage to reproduce it. but it happens, and a lot.
Can you please make the DB files available also in the former urls?
This is very **urgent** for us.

Thanks!

**Comment by bluesmoon** [comment]
The DB files are managed by MaxMind, we don't have control over them or the URLs they use.

**Comment by RazYahkovnia** [comment]
Thanks for the response,

So after we updated geoip-lite to 1.3.7, we are getting the error I mentioned.
Could you assist?

**Comment by bluesmoon** [comment]
@ar2rsawseen any idea?

**Comment by RazYahkovnia** [comment]
Any updates?

**Comment by ar2rsawseen** [comment]
Hello, does it happen with original files provided with the package?
Or only after you update the database to new data?

**Comment by ar2rsawseen** [comment]
Does this happen for you with this example too?
https://github.com/bluesmoon/node-geoip/issues/181

**Comment by RazYahkovnia** [comment]
It happens after an update.

**Comment by ar2rsawseen** [comment]
Can you put a log on ip address, so we could see any specific IP address with which it happens?
In case of https://github.com/bluesmoon/node-geoip/issues/181, this happened due to using new js files with old DB files or having corrupt update

**Comment by RazYahkovnia** [comment]
Issue fixed, the update DB didn't work on our servers (inside issue) and this is why we got the errors.
Thanks for the help!!
