### ISSUE TITLE
Error: The value of "offset" is out of range

### ISSUE THREAD

**Issue by shlomisas** [bluesmoon/node-geoip#181]
When using the module for `193.83.231.160` IP:

```
try{
        const ip = require('geoip-lite').lookup('193.83.231.160');
        debugger;
    }catch(e){
        debugger;
    }
```

I'm getting the following error:

```
The value of "offset" is out of range. It must be >= 0 and <= 41062780. Received 46699669
```
![image](https://user-images.githubusercontent.com/839774/59788989-9eb71a00-92d5-11e9-909f-a8817705c72b.png)

When I'm checking it with some external site (https://www.ultratools.com/tools/geoIp) it gives me a valid IP form Austria.

I'm using version 1.3.7

Any idea why?

**Comment by ar2rsawseen** [comment]
I have installed latest npm package and tried your ip address, it works
Then I tried updating db with new ip addresses and it works after that too.
```
{ range: [ 3243501056, 3243501567 ],
  country: 'AT',
  region: '5',
  eu: '1',
  timezone: 'Europe/Vienna',
  city: 'Salzburg',
  ll: [ 47.8008, 13.0443 ],
  metro: 0,
  area: 100 }
Startup: 380ms, exec: 28ms
```
Did you update db? Maybe something happened in between?
What other distinguishable things there might be? Nodejs Version?
Maybe you can try updating database again with force flag?

**Comment by ar2rsawseen** [comment]
Since lookup is in RAM, maybe there are problems there, not enough RAM when loading buffer?

**Comment by shlomisas** [comment]
Yes, you right, I had outdated databases (because I'm using the `global.geodatadir` from reasons i do not really remember :) ), updated the DB helped.

Thank you!
