### ISSUE TITLE
sometimes timezone is null although location (long, lat) is available 

### ISSUE THREAD

**Issue by tkeidar** [bluesmoon/node-geoip#182]
For some IP addresses, there is no timezone although the location by longitude, latitude is available and it's possible to calculate the timezone accordingly.

some IPs for example:
120.156.101.62
31.4.135.51
174.194.99.1

**Comment by bluesmoon** [comment]
I don't see it on the MaxMind website either:


IP Address | Country Code | Location | Postal Code | Approximate Coordinates* | Accuracy Radius (km) | ISP | Organization | Domain | Metro Code
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
120.156.101.62 | AU | Cherrybrook,New South Wales,Australia,Oceania | 2126 | -33.7363,151.0309 | 100 | Telstra Internet | Telstra Internet | telstra.net |  
31.4.135.51 | ES | Spain,Europe |   | 40.4172,-3.684 | 200 | Vodafone Spain | Vodafone Spain | airtel.net |  
174.194.99.1 | US | United States,North America |   | 37.751,-97.822 | 1000 | Verizon Wireless | Verizon Wireless | myvzw.com |

**Comment by tkeidar** [comment]
but you do have the exact location, city and even postal code in some cases, isn't it enough to retrieve the timezone?

**Comment by bluesmoon** [comment]
We only provide what's in the MaxMind DB. It doesn't make sense for us to add a TZ lookup in here when there are already other node modules that do it (eg: https://www.npmjs.com/package/tz-lookup). If we did the lookup it would probably just outsource to something like that, which means we'd end up pulling in the dependency even for folks who don't need it.

**Comment by tkeidar** [comment]
thank you @bluesmoon!

**Comment by oschwald** [comment]
I don't believe the website shows the time zone for any IP. When testing those IPs with the latest version of the GeoLite2 City MMDB, I see a time zone. If a time zone is indeed missing from the CSV, please email [support@maxmind.com](mailto:support@maxmind.com).

**Comment by bluesmoon** [comment]
I updated to the latest city database, and the timezone shows up.  Can you try running `updatedb` and see if that fixes the issue?

**Comment by tkeidar** [comment]
Thanks, @bluesmoon1 -  it fixed it! 😃
how often do you recommend to run DB update?

**Comment by bluesmoon** [comment]
Maxmind updates once a month.
