### ISSUE TITLE
Missing country_code for few IPs

### ISSUE THREAD

**Issue by igauravsehrawat** [bluesmoon/node-geoip#185]
Hi,
Two IPs are returning empty country_code
1. `88.221.141.15`
2. `95.100.125.20`

Interesting thing is GeoIP2 demo is also return empty country_code.
<img width="821" alt="Screen Shot 2019-12-11 at 18 00 35" src="https://user-images.githubusercontent.com/3696327/70642944-6d922380-1c40-11ea-8c77-1facbe5962ca.png">

How can this resolved? Any ideas?

Thanks

**Comment by bluesmoon** [comment]
Talk to MaxMind. We don't control the data. If we match what MaxMind returns, then the library is working as designed.

**Comment by bluesmoon** [comment]
FWIW, neither of these IPs are end user IPs. They belong to Akamai (a global CDN), so their actual location may not be disclosed. You can do a `whois` lookup on the IPs to find the owner.

**Comment by igauravsehrawat** [comment]
Thanks @bluesmoon
