### ISSUE TITLE
Changes to GeoLite2 license and distribution have effect for this project

### ISSUE THREAD

**Issue by 2shortplanks** [bluesmoon/node-geoip#186]
Due to upcoming data privacy regulations, MaxMind are making significant changes to how users access free MaxMind GeoLite2 databases starting December 30, 2019. The databases will continue to be available without charge and for redistribution. However, you will be required to create an account and use a license key to download the databases, and agree to a new EULA that addresses applicable data privacy regulations.

Learn more on the MaxMind blog: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/.

Mark Fowler
MaxMind

**Comment by ar2rsawseen** [comment]
Hello @2shortplanks 
are there limits to these accounts?
would it be ok to create a single account for this library, or each user of the library would need to create their own accounts and we would need to make it as a configuration option?

**Comment by bluesmoon** [comment]
Thanks for the info. Will add this to our README.

**Comment by bluesmoon** [comment]
Another question is whether this applies to the version of the library that's already in our repository? That's a fairly old version.

**Comment by 2shortplanks** [comment]
> are there limits to these accounts?
> would it be ok to create a single account for this library, or each user of the library would need to create their own accounts and we would need to make it as a configuration option?

Thanks for your quick reply!  The full text of the license will be posted on December 23rd (Monday) and linked from https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/.

Let me know if that doesn't address these questions

**Comment by 2shortplanks** [comment]
> Another question is whether this applies to the version of the library that's already in our repository? That's a fairly old version.

With regard to the existing databases, these were distributed under the Creative Commons Attribution-ShareAlike 4.0 International License which still applies to all further distribution.  However keep in mind that MaxMind itself will no longer distribute these existing databases, and entities that are covered by the CCPA will have responsibilities when distributing these older databases under California law which you should obtain your own legal counsel to determine.

**Comment by getorca** [comment]
Sounds like you can still distribute the updated database with projects, it's still licensed under "Creative Commons Corporation Attribution-ShareAlike 4.0 International License (the “Creative Commons License”)"

A couple options to keep this package updated:

1 - build more frequently with the updated DB

or (probably preferable)

2 - allow ```npm run-script updatedb``` to take config options to download the DB

**Comment by austinshenk** [comment]
Is this issue being worked on or is a workaround available? We rely on updating the DB during our build process and we're wanting to get an idea on the steps we could take in regards to this. We're considering just disabling the DB update and using the old data for now.

**Comment by justinpage** [comment]
#187 resolves this issue. I think we can close this.

**Comment by justinpage** [comment]
Created a pull request updating the README to include new changes from #187 

https://github.com/bluesmoon/node-geoip/pull/188
