### ISSUE TITLE
Add currency code

### ISSUE THREAD

**Issue by ramioooz** [bluesmoon/node-geoip#189]
Hello, bluesmoon,

thank you for sharing this nice package,
it would be much nicer if you can add country code in the returned JSON object.

I hope you can do it soon,
My regards,

**Comment by ar2rsawseen** [comment]
Hello
you mean currency or country?
Eitherway country is already included, and I don't think currency is provided in the source database, so not possible to add it. Sorry :)

**Comment by bluesmoon** [comment]
Note that if you do want currency code, better to use https://www.npmjs.com/package/currency-codes

**Comment by ramioooz** [comment]
I managed to get the currency code from country code provided by goeip-lite using another simple package : 
https://www.npmjs.com/package/iso-country-currency

like this : 

npm install geoip-lite --save
npm install iso-country-currency --save

```
var geoip = require('geoip-lite');
var isoCountryCurrency = require('iso-country-currency');

var ip = req.connection.remoteAddress;
var geo = geoip.lookup(ip);

if (geo) {
    var currencyInfo = isoCountryCurrency.getAllInfoByISO(geo.country);
    var returnObj = {
        ip: ip,
        countryCode: geo.country,
        currencyCode: currencyInfo.currency,
    };
    console.log(returnObj);
} else {
    console.log('geo not found');
}
```

Hope this help,
Thank you

**Comment by bluesmoon** [comment]
whatever works for you
