### ISSUE TITLE
Failed to reflect some Germany ip?

### ISSUE THREAD

**Issue by richzw** [bluesmoon/node-geoip#193]
We found the following Germany ip failed to find.

'45.145.239.195'
'91.212.40.24'

Both of them return `null`. However, per https://ip.sb/, those two ips are belong to Germany.

Is there anything am I missing?

**Comment by ar2rsawseen** [comment]
Usually, it is because 
1) difference between free and paid databases (we use a free one)
or
2) your database is out of date, you can try updating it, but it needs license key from maxmind

**Comment by richzw** [comment]
@ar2rsawseen , Thank you very much for your reply. We will try new database.
