### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/data/geoip-country.dat

### ISSUE THREAD

**Issue by stevemarksd** [bluesmoon/node-geoip#195]
Getting this only on docker with aws `Error: ENOENT: no such file or directory, open '/data/geoip-country.dat'`

```
# Alpine system
FROM node:12.9.1-alpine
RUN yarn config set no-progress true
RUN yarn install
```

package json

```
{
  "name": "123",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "socket.io": "^2.1.1",
    "sequelize": "^4.38.0",
    "pg": "^7.4.3",
    "geoip-lite": "^1.4.0",
    "discord.js": "11.5.1"
  }
}

```

This is a compiled script with webpack on server side, so I have a feeling you something might not be handling the file path correctly

**Comment by stevemarksd** [comment]
was something wrong on my code.

**Comment by WeslyG** [comment]
For my webpack config help this config 
```
  node: {
    __dirname: true
  },
```
refs https://stackoverflow.com/questions/40775712/webpack-bundle-enoent-no-such-file-or-directory-fs-readdirsync

**Comment by CodeWithOz** [comment]
@WeslyG do you have an idea of the equivalent of that config option using esbuild?

**Comment by DynamicRemo** [comment]
this is usually a cache kinda issue... you just have to clean up your node_module folder and run `npm install` again to have cleaned up repository. Cheers!

**Comment by LukeXF** [comment]
This didn't work

> this is usually a cache kinda issue... you just have to clean up your node_module folder and run `npm install` again to have cleaned up repository. Cheers!

**Comment by LukeXF** [comment]
using `etsc.config.js` and adding this value fixed it:

```
	external: [
			'geoip-lite'
		]
```

**Comment by PascalPixel** [comment]
Webpack can't resolve the paths to the .dat files automatically with NextJS, _perhaps_ because the new global variable option trips up the resolution, I don't know, but manually copying the .dat files worked for me;

```next.config.js
const CopyWebpackPlugin = require("copy-webpack-plugin");

/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.plugins.push(
        new CopyWebpackPlugin({
          patterns: [
            {
              from: "node_modules/geoip-lite/data/geoip-country.dat",
              to: "data/geoip-country.dat",
            },
            {
              from: "node_modules/geoip-lite/data/geoip-country6.dat",
              to: "data/geoip-country6.dat",
            },
          ],
        }),
      );
    }
    return config;
  },
};

module.exports = nextConfig;
```

**Comment by kuncevic** [comment]
Just opened a related discussion here https://github.com/orgs/vercel/discussions/5182
