### ISSUE TITLE
License key version to choose

### ISSUE THREAD

**Issue by teyou** [bluesmoon/node-geoip#196]
Should we choose the 1st option (i.e. v3.1.1 or newer) when generating license key for this package? 
<img width="786" alt="license" src="https://user-images.githubusercontent.com/1115155/75647750-e4abe680-5c88-11ea-803c-742acfa78a6e.png">

**Comment by ar2rsawseen** [comment]
Hello
yes, I think I tested it with new and it worked as expected and new one is recommended for security purposes

**Comment by teyou** [comment]
Cool, thanks
