### ISSUE TITLE
Maxmind API URL is changing

### ISSUE THREAD

**Issue by kmcnerney-salesforce** [bluesmoon/node-geoip#198]
On June 1st, Maxmind is changing the URL that this package uses to download the database.

The URL needs to be updated from 
`https://download.maxmind.com/app/geoip_download`
to
`https://geoip.maxmind.com/app/geoip_download`

Can someone please make this change and release a new version? 

<img width="556" alt="Screen Shot 2020-03-15 at 2 55 30 PM" src="https://user-images.githubusercontent.com/44412542/76708511-bd640900-66cd-11ea-92c8-4648810b7d6f.png">

**Comment by ar2rsawseen** [comment]
Added PR here
https://github.com/bluesmoon/node-geoip/pull/199

**Comment by ianwijma** [comment]
Probably related, but the updatedb command is throwing errors:
```cash
cd node_modules/geoip-lite && npm run-script updatedb license_key=YOUR_LICENSE_KEY
```
It gives the following output:
```
Checking  GeoLite2-Country-CSV.zip
ERROR: HTTP Request Failed [301 Moved Permanently]
```

**Comment by bluesmoon** [comment]
I pushed a new release yesterday, can you check with that?

>

**Comment by ar2rsawseen** [comment]
Please reopen the issue if you still experience the problem
