### ISSUE TITLE
🎉Credits

### ISSUE THREAD

**Issue by A-Tokyo** [bluesmoon/node-geoip#201]
Thank you so much for the amazing work! Really helped me out

I made use of this library in a microservice to avoid increasing the size of the core backend app, and to also use on the frontend if need be.

Here's the [repo](https://github.com/A-Tokyo/micro-geoip-lite) and here's a [demo](https://geoip-lite.now.sh/)

It'd not have been possible without your great work, thanks!

**Comment by ar2rsawseen** [comment]
Thank you for letting us know :)
