### ISSUE TITLE
wrong data when using watch

### ISSUE THREAD

**Issue by parisholley** [bluesmoon/node-geoip#69]
I've been noticing that at random, geoip look ups were being skewed (ie: my ip was pointing to a completely different place). I believe the issue, is that the npm update-db script actually takes about ~10 minutes for it to complete (GeoLiteCity-latest takes a long time), and when switching between files, not really sure what is going on. I was able to reproduce with this script:

```
var geoip = require('geoip-lite');

setInterval(function(){
    console.log(geoip.lookup('75.82.117.180'));
}, 2000);

geoip.startWatchingDataUpdate();
```

I then run the update in the background, and things work great. But as soon as the update completes (i'd say about a minute later), the lookup output changes.

I'm going to try upping the timeout on the watcher to 15 minutes instead of a minute and see if that helps.

**Comment by ar2rsawseen** [comment]
I think this should be fixed by this: https://github.com/bluesmoon/node-geoip/pull/167

**Comment by ar2rsawseen** [comment]
PR merged, will publish new release
