### ISSUE TITLE
Doesn't play nicely with node-webkit

### ISSUE THREAD

**Issue by isdampe** [bluesmoon/node-geoip#76]
Howdy.

Not sure what's going on here. When I run a script with the following via node-webkit, I get null. When I run with node (via terminal), I get a result.

```
var geoip = require('geoip-lite');  
var res = geoip.lookup("8.8.8.8");  
console.log(res);
```

**Comment by bluesmoon** [comment]
can you trace through the code to see what's happening?

**Comment by isdampe** [comment]
I'll have a deeper look later, it's a little hard with node-webkit because it seems to be quite selective what is showed when debugging

**Comment by bluesmoon** [comment]
throw in some console.log statements in the geoip code

**Comment by isdampe** [comment]
Even then node-webkit doesn't seem to log all existing console.log statements (maybe due to the fact i tries to reroute the io stream?)

So far I've determined that the paths to the data files are still correct, haven't been relatively incorrect.

Is there a minimum version of node required?

**Comment by isdampe** [comment]
It appears that when running under node-webkit, around line 330ish, these values are different:

```
cache4.lastLine = (datSize / cache4.recordSize) - 1;
cache4.lastIP = cache4.mainBuffer.readUInt32BE((cache4.lastLine * cache4.recordSize) + 4);
cache4.firstIP = cache4.mainBuffer.readUInt32BE(0);
console.log(cache4.lastIP);
```

Terminal based node result shows 3758096383, when in node-webkit, it shows -536870913

**Comment by bluesmoon** [comment]
looks like a difference in how the two types of node read in files from
disk.  I know we did have problems with older versions of node (prior to
0.10), so could it be that node-webkit is based off an older version?

**Comment by ar2rsawseen** [comment]
If issue is still valid, please reopen
