### ISSUE TITLE
iconv-lite dependency

### ISSUE THREAD

**Issue by ecwyne** [bluesmoon/node-geoip#79]
Current dependency is [~0.2.11](https://github.com/bluesmoon/node-geoip/blob/master/package.json#L21)
Current package is [0.4.7](https://www.npmjs.com/package/iconv-lite)

**Comment by bluesmoon** [comment]
sure, submit a pull request.

**Comment by ecwyne** [comment]
created

https://github.com/bluesmoon/node-geoip/pull/80
