### ISSUE TITLE
Reduce RAM footprint by just using country?

### ISSUE THREAD

**Issue by chrisjhoughton** [bluesmoon/node-geoip#83]
First of all - great library, makes a complicated thing so simple.

For our project, all we're looking to do is group customers by country. Is it possible to use this module without having to load in all the other more specific region and metro code data to reduce the memory footprint?

Clearly it'll work with a fork, but curious to see if there's another way.

**Comment by bluesmoon** [comment]
I think if you replace the city data files with empty files, it should work.

**Comment by chrisjhoughton** [comment]
Awesome, will give that go thanks
