### ISSUE TITLE
GeoLite2

### ISSUE THREAD

**Issue by jstayton** [bluesmoon/node-geoip#85]
Hi Philip,

Thanks so much for your work on this package!

When I followed the link in the `README` to MaxMind's GeoLite page, it has a banner saying the newer [GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/) data is now recommended.

Any plans to support GeoLite2?

Thanks!

**Comment by bluesmoon** [comment]
Not at the moment, but if someone were to send in a patch, I'd be happy to merge it in _tout de suite_

**Comment by YasharF** [comment]
There is an official deprecation notice posted at https://dev.maxmind.com/geoip/geoip2/geolite2 : 

- March 2018 GeoLite Legacy dataset build is the last build; new builds are going to be only on GeoLite2, etc.
- On January 2, 2019, the last build of the legacy dataset will be removed from their website.

**Comment by bluesmoon** [comment]
No one's submitted a patch yet, and I don't have the time to make the changes myself.

**Comment by mastermatt** [comment]
This was fixed with https://github.com/bluesmoon/node-geoip/pull/138
