### ISSUE TITLE
Why does updatedb require npm_package_config_update

### ISSUE THREAD

**Issue by servel333** [bluesmoon/node-geoip#86]
When I look at the top of `scripts/updatedb.js` I see this code:

    if(!process.env.npm_package_config_update){
      return;
    }

I can't find any documentation on the environment variable `npm_package_config_update` nor can I see any place in the code where this is set. Where does this environment variable come from?

**Comment by bluesmoon** [comment]
You set it via npm. It was added because many people do not want update to
run on install as it can cause a timeout for automated installs.

**Comment by servel333** [comment]
does npm set that variable when you run this script like this?

    # in node_modules/geoip-lite/
    npm run updatedb

I can't find any documentation on this variable and there doesn't seem to be any place in the `geoip-lite` code that sets it. I guess my main question is, how does that variable get set when I run the above command?

For a little background: I'm using geoip-lite in my node project and I want to add a job (using `node-schedule`) that runs this script on a regular basis so the data files are kept updated. When I run the script on the shell (using `shelljs` or `child_process`) it seems to at least start up (with errors I'm currently investigating) but when I run it using `require('geoip-lite/scripts/updatedb.js')` the script exits silently with no error. Upon investigation I see this variable is blocking the script from running. I had to change my code to this:

      process.env.npm_package_config_update = true;
      require('geoip-lite/scripts/updatedb.js');
      delete process.env.npm_package_config_update;

Is this a recommended way to get this script running in my node project that depends on `geoip-lite`?

Also, an answer 4 minutes later is amazingly fast! Thanks!

**Comment by bluesmoon** [comment]
So you can export an environment variable from your shell before starting your code like this:

```bash
npm_package_config_update=1 node program.js
```

or from inside your node.js app, using the code you pasted above.

however, the recommended way to get this update to happen is to just use `cron` and add an entry in your `crontab` to run it say once a week.

**Comment by servel333** [comment]
Understood about Cron. I can't use it because we are using Docker and it's not trivial to set up Cron in Docker. I still don't understand where the `npm_package_config_update` variable comes from when you run the script like this:

    # in node_modules/geoip-lite/
    npm run updatedb

but I don't really need to to get it working. Thanks for your help.

**Comment by bluesmoon** [comment]
It's set by this section in `package.json`:
```
	},
	"config": {
		"update": true
	},
```

**Comment by servel333** [comment]
And I just found https://github.com/npm/npm/blob/180da67c9fa53103d625e2f031626c2453c7ebcd/doc/misc/npm-scripts.md#packagejson-vars that explains it too. Thank you very much.
