### ISSUE TITLE
My ip is resulting in the wrong country....  time to update these files...

### ISSUE THREAD

**Issue by Ajar-Ajar** [bluesmoon/node-geoip#87]
Hi, using those files, my ip gives a wrong country which is a major issue...
Using the MaxMind demo - the same ip yields the correct country, therefore it is maybe time to update those data files... how can it be done manually? I would like to contribute some effort for this purpose.
Cheers
Ajar

**Comment by bluesmoon** [comment]
You can run the update script. Instructions are in the README file. This should be run once a month.

**Comment by mohamed-ahmed** [comment]
@Ajar-Ajar did that fix it for you?

**Comment by sumeetkpatel** [comment]
I am also curious about updating.
Does that script just download the database that is still 9 months old or does it update it something newer than that?

**Comment by bluesmoon** [comment]
it downloads the latest files from MaxMind.

**Comment by jonathanong** [comment]
tried to update, but tests are failing as test IP locations have changed. if anyone would like to take a shot at finding alternative IPs to use as test fixtures, that would be great!

**Comment by Phanindra48** [comment]
@jonathanong - i updated these files and fixed related test cases.
Please have a look at this PR https://github.com/bluesmoon/node-geoip/pull/114
