### ISSUE TITLE
IP2Location LITE Support

### ISSUE THREAD

**Issue by m-cameron** [bluesmoon/node-geoip#89]
@bluesmoon

Do you have plan to support the IP2Location LITE database? It has the ZIP code information which is an advantage compare to GeoIP.

http://lite.ip2location.com

**Comment by bluesmoon** [comment]
MaxMind's GeoIP already supports ZIP code, we just didn't include it in geoip-lite because it would make the library not lite any more ;)  Feel free to submit a patch that does not reduce performance.
