### ISSUE TITLE
Is there a way to tell if the module recognised and refreshed upon data files updates on fs?

### ISSUE THREAD

**Issue by onne** [bluesmoon/node-geoip#90]
I used `geoip.startWatchingDataUpdate();` together with `npm run-script updatedb` yet I don't know if it really refreshed the data in memory.
Is there any way to tell if the refresh actually happened?

**Comment by bluesmoon** [comment]
@ctalkington @GUI can either of you answer this?

**Comment by ar2rsawseen** [comment]
I think this should be fixed by this: https://github.com/bluesmoon/node-geoip/pull/167

**Comment by ar2rsawseen** [comment]
You should be able to provide callback to that function, which will be called every time data is refreshed.

```
geoip.startWatchingDataUpdate(function(){
    console.log("Data refreshed");
});
```
