### ISSUE TITLE
centos install failed: shasum check failed

### ISSUE THREAD

**Issue by hisune** [bluesmoon/node-geoip#91]
`npm install geoip-lite`

npm ERR! Linux 2.6.32-358.6.2.el6.x86_64
npm ERR! argv "node" "/usr/local/node/bin/npm" "install" "geoip-lite"
npm ERR! node v0.10.36
npm ERR! npm  v2.14.3

npm ERR! shasum check failed for /tmp/npm-8116-ad9e27de/registry.npmjs.org/pullstream/-/pullstream-0.0.4.tgz
npm ERR! Expected: 41d83c446d290e2f2eb9b681d3f3b56fee88a0af
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/pullstream/-/pullstream-0.0.4.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /data/nginx/wwwroot/click/npm-debug.log

**Comment by bluesmoon** [comment]
Contact npm about this issue.  It's not related to geoip-lite.
