### ISSUE TITLE
Database updating via HTTPS?

### ISSUE THREAD

**Issue by METACEO** [bluesmoon/node-geoip#92]
Instead of the `http` module, could the `npm run-script updatedb` utilize `https` and its `.get`?.. could this at least be optional, or on by default? Maxmind supports all the below over **HTTPS**...
`https://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip`
`https://geolite.maxmind.com/download/geoip/database/GeoIPv6.csv.gz`
`https://geolite.maxmind.com/download/geoip/database/GeoLiteCity_CSV/GeoLiteCity-latest.zip`
`https://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.csv.gz`

...and I've retested after making the below change without any issues (the download took a little while longer to begin, a second or two at most.)

```javascript
var http = require('https');
```

**Comment by chill117** [comment]
I agree. HTTPS should be the default protocol for these requests.

**Comment by bluesmoon** [comment]
can you send this as a pull request?  I'll be happy to merge it in.  I'm on the road too much to make the changes myself.

**Comment by chill117** [comment]
Will do!
