### ISSUE TITLE
Method to call updatedb script

### ISSUE THREAD

**Issue by estliberitas** [bluesmoon/node-geoip#98]
Hi guys. I would like to know your opinion, if it would be cool to add a method which would execute updatedb script? So we already have API to watch for updates, why not have another one to call update from JavaScript? I would like to submit a PR if you agree it's worth implementing.

@bluesmoon

**Comment by bluesmoon** [comment]
Sure if you like, though I think this is better done via `crontab`

**Comment by jonathanong** [comment]
or at least make `scripts/updatedb.js` a public file. easy enough to do `"postinstall": "node node_modules/geoip-lite/scripts/updatedb.js"` in your package.json's scripts

**Comment by jonathanong** [comment]
though https://github.com/bluesmoon/node-geoip/commit/095bf4088acaef08dbe4fefb2360a44c8156fc17#diff-64bfcd0a229c3ba89c85c6c12c10805fR5 makes it unnecessarily difficult

**Comment by jonathanong** [comment]
you might be interested in https://github.com/jonathanong/geoip3

**Comment by bluesmoon** [comment]
@jonathanong I can give you commit access to this repo if you're able to maintain it.  If you know how I can also give you access to update npm, that will be good, else I can keep updating npm.

**Comment by jonathanong** [comment]
@bluesmoon thanks. `npm owner add jongleberry geoip-lite`

**Comment by jonathanong** [comment]
@estliberitas https://github.com/bluesmoon/node-geoip#built-in-updater added a few ways to call the updater.

**Comment by estliberitas** [comment]
@jonathanong wow, thanks!
