### ISSUE TITLE
Cannot extract GeoIPCountryCSV.zip

### ISSUE THREAD

**Issue by ivanakimov** [bluesmoon/node-geoip#99]
Trying to update the db, but it keeps crashing for some reason. This always worked for me before, but not anymore. Did something change?

```
geoip-lite git:dev ❯ npm run-script updatedb

> geoip-lite@1.1.6 updatedb /tmp/node_modules/geoip-lite
> node scripts/updatedb.js

Retrieving GeoIPCountryCSV.zip ... DONE
Extracting GeoIPCountryCSV.zip ...%
geoip-lite git:dev ❯ 
```

**Comment by ivanakimov** [comment]
Any update on this? Still not working...

**Comment by GriffinSauce** [comment]
Did some digging, it appears the unzip module isn't emitting the "end" event. 

It's a [known](https://github.com/EvanOxfeld/node-unzip/issues/21) [issue](https://github.com/EvanOxfeld/node-unzip/issues/20) but the repo is pretty stale so I don't expect that to be fixed soon.

It seems the best solution would be to replace unzip with an alternative.

**Comment by bluesmoon** [comment]
Switching out unzip is being tracked in #107 so I'm closing this.
